/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACausaSeCausaSe extends PCausaSe
{
    private PComandos _comandos_;
    private PComando _comando_;
    private PComandoSenao _comandoSenao_;

    public ACausaSeCausaSe()
    {
        // Constructor
    }

    public ACausaSeCausaSe(
        @SuppressWarnings("hiding") PComandos _comandos_,
        @SuppressWarnings("hiding") PComando _comando_,
        @SuppressWarnings("hiding") PComandoSenao _comandoSenao_)
    {
        // Constructor
        setComandos(_comandos_);

        setComando(_comando_);

        setComandoSenao(_comandoSenao_);

    }

    @Override
    public Object clone()
    {
        return new ACausaSeCausaSe(
            cloneNode(this._comandos_),
            cloneNode(this._comando_),
            cloneNode(this._comandoSenao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACausaSeCausaSe(this);
    }

    public PComandos getComandos()
    {
        return this._comandos_;
    }

    public void setComandos(PComandos node)
    {
        if(this._comandos_ != null)
        {
            this._comandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandos_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    public PComandoSenao getComandoSenao()
    {
        return this._comandoSenao_;
    }

    public void setComandoSenao(PComandoSenao node)
    {
        if(this._comandoSenao_ != null)
        {
            this._comandoSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSenao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandos_)
            + toString(this._comando_)
            + toString(this._comandoSenao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandos_ == child)
        {
            this._comandos_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        if(this._comandoSenao_ == child)
        {
            this._comandoSenao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandos_ == oldChild)
        {
            setComandos((PComandos) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        if(this._comandoSenao_ == oldChild)
        {
            setComandoSenao((PComandoSenao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
