/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AComandoRepitaComando extends PComando
{
    private final LinkedList<PComando> _comando_ = new LinkedList<PComando>();
    private PCondicaoSe _condicaoSe_;

    public AComandoRepitaComando()
    {
        // Constructor
    }

    public AComandoRepitaComando(
        @SuppressWarnings("hiding") List<?> _comando_,
        @SuppressWarnings("hiding") PCondicaoSe _condicaoSe_)
    {
        // Constructor
        setComando(_comando_);

        setCondicaoSe(_condicaoSe_);

    }

    @Override
    public Object clone()
    {
        return new AComandoRepitaComando(
            cloneList(this._comando_),
            cloneNode(this._condicaoSe_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoRepitaComando(this);
    }

    public LinkedList<PComando> getComando()
    {
        return this._comando_;
    }

    public void setComando(List<?> list)
    {
        for(PComando e : this._comando_)
        {
            e.parent(null);
        }
        this._comando_.clear();

        for(Object obj_e : list)
        {
            PComando e = (PComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comando_.add(e);
        }
    }

    public PCondicaoSe getCondicaoSe()
    {
        return this._condicaoSe_;
    }

    public void setCondicaoSe(PCondicaoSe node)
    {
        if(this._condicaoSe_ != null)
        {
            this._condicaoSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condicaoSe_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comando_)
            + toString(this._condicaoSe_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comando_.remove(child))
        {
            return;
        }

        if(this._condicaoSe_ == child)
        {
            this._condicaoSe_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PComando> i = this._comando_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._condicaoSe_ == oldChild)
        {
            setCondicaoSe((PCondicaoSe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
