/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpLogMenorExpLogicaMaior extends PExpLogicaMaior
{
    private PExpLogicaMenor _expLogicaMenor_;

    public AExpLogMenorExpLogicaMaior()
    {
        // Constructor
    }

    public AExpLogMenorExpLogicaMaior(
        @SuppressWarnings("hiding") PExpLogicaMenor _expLogicaMenor_)
    {
        // Constructor
        setExpLogicaMenor(_expLogicaMenor_);

    }

    @Override
    public Object clone()
    {
        return new AExpLogMenorExpLogicaMaior(
            cloneNode(this._expLogicaMenor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpLogMenorExpLogicaMaior(this);
    }

    public PExpLogicaMenor getExpLogicaMenor()
    {
        return this._expLogicaMenor_;
    }

    public void setExpLogicaMenor(PExpLogicaMenor node)
    {
        if(this._expLogicaMenor_ != null)
        {
            this._expLogicaMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaMenor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogicaMenor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogicaMenor_ == child)
        {
            this._expLogicaMenor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogicaMenor_ == oldChild)
        {
            setExpLogicaMenor((PExpLogicaMenor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
