/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpressaoDirDivisaoExpressaoDir extends PExpressaoDir
{
    private PExpressaoDir _expressaoDir_;
    private TDiv _div_;
    private PExpressaoFator _expressaoFator_;

    public AExpressaoDirDivisaoExpressaoDir()
    {
        // Constructor
    }

    public AExpressaoDirDivisaoExpressaoDir(
        @SuppressWarnings("hiding") PExpressaoDir _expressaoDir_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PExpressaoFator _expressaoFator_)
    {
        // Constructor
        setExpressaoDir(_expressaoDir_);

        setDiv(_div_);

        setExpressaoFator(_expressaoFator_);

    }

    @Override
    public Object clone()
    {
        return new AExpressaoDirDivisaoExpressaoDir(
            cloneNode(this._expressaoDir_),
            cloneNode(this._div_),
            cloneNode(this._expressaoFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressaoDirDivisaoExpressaoDir(this);
    }

    public PExpressaoDir getExpressaoDir()
    {
        return this._expressaoDir_;
    }

    public void setExpressaoDir(PExpressaoDir node)
    {
        if(this._expressaoDir_ != null)
        {
            this._expressaoDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoDir_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PExpressaoFator getExpressaoFator()
    {
        return this._expressaoFator_;
    }

    public void setExpressaoFator(PExpressaoFator node)
    {
        if(this._expressaoFator_ != null)
        {
            this._expressaoFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoDir_)
            + toString(this._div_)
            + toString(this._expressaoFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoDir_ == child)
        {
            this._expressaoDir_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._expressaoFator_ == child)
        {
            this._expressaoFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoDir_ == oldChild)
        {
            setExpressaoDir((PExpressaoDir) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._expressaoFator_ == oldChild)
        {
            setExpressaoFator((PExpressaoFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
