/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpSomaExpressaoEsq extends PExpressaoEsq
{
    private PExpressaoEsq _expressaoEsq_;
    private TSum _sum_;
    private PExpressaoDir _expressaoDir_;

    public AExpSomaExpressaoEsq()
    {
        // Constructor
    }

    public AExpSomaExpressaoEsq(
        @SuppressWarnings("hiding") PExpressaoEsq _expressaoEsq_,
        @SuppressWarnings("hiding") TSum _sum_,
        @SuppressWarnings("hiding") PExpressaoDir _expressaoDir_)
    {
        // Constructor
        setExpressaoEsq(_expressaoEsq_);

        setSum(_sum_);

        setExpressaoDir(_expressaoDir_);

    }

    @Override
    public Object clone()
    {
        return new AExpSomaExpressaoEsq(
            cloneNode(this._expressaoEsq_),
            cloneNode(this._sum_),
            cloneNode(this._expressaoDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpSomaExpressaoEsq(this);
    }

    public PExpressaoEsq getExpressaoEsq()
    {
        return this._expressaoEsq_;
    }

    public void setExpressaoEsq(PExpressaoEsq node)
    {
        if(this._expressaoEsq_ != null)
        {
            this._expressaoEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoEsq_ = node;
    }

    public TSum getSum()
    {
        return this._sum_;
    }

    public void setSum(TSum node)
    {
        if(this._sum_ != null)
        {
            this._sum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sum_ = node;
    }

    public PExpressaoDir getExpressaoDir()
    {
        return this._expressaoDir_;
    }

    public void setExpressaoDir(PExpressaoDir node)
    {
        if(this._expressaoDir_ != null)
        {
            this._expressaoDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoEsq_)
            + toString(this._sum_)
            + toString(this._expressaoDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoEsq_ == child)
        {
            this._expressaoEsq_ = null;
            return;
        }

        if(this._sum_ == child)
        {
            this._sum_ = null;
            return;
        }

        if(this._expressaoDir_ == child)
        {
            this._expressaoDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoEsq_ == oldChild)
        {
            setExpressaoEsq((PExpressaoEsq) newChild);
            return;
        }

        if(this._sum_ == oldChild)
        {
            setSum((TSum) newChild);
            return;
        }

        if(this._expressaoDir_ == oldChild)
        {
            setExpressaoDir((PExpressaoDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
