/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpeNaoExpLogicaEsq extends PExpLogicaEsq
{
    private TNao _nao_;
    private PExpLogicaEsq _expLogicaEsq_;

    public AExpeNaoExpLogicaEsq()
    {
        // Constructor
    }

    public AExpeNaoExpLogicaEsq(
        @SuppressWarnings("hiding") TNao _nao_,
        @SuppressWarnings("hiding") PExpLogicaEsq _expLogicaEsq_)
    {
        // Constructor
        setNao(_nao_);

        setExpLogicaEsq(_expLogicaEsq_);

    }

    @Override
    public Object clone()
    {
        return new AExpeNaoExpLogicaEsq(
            cloneNode(this._nao_),
            cloneNode(this._expLogicaEsq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpeNaoExpLogicaEsq(this);
    }

    public TNao getNao()
    {
        return this._nao_;
    }

    public void setNao(TNao node)
    {
        if(this._nao_ != null)
        {
            this._nao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nao_ = node;
    }

    public PExpLogicaEsq getExpLogicaEsq()
    {
        return this._expLogicaEsq_;
    }

    public void setExpLogicaEsq(PExpLogicaEsq node)
    {
        if(this._expLogicaEsq_ != null)
        {
            this._expLogicaEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaEsq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nao_)
            + toString(this._expLogicaEsq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nao_ == child)
        {
            this._nao_ = null;
            return;
        }

        if(this._expLogicaEsq_ == child)
        {
            this._expLogicaEsq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nao_ == oldChild)
        {
            setNao((TNao) newChild);
            return;
        }

        if(this._expLogicaEsq_ == oldChild)
        {
            setExpLogicaEsq((PExpLogicaEsq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
