/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpeMenorExpLogicaEsq extends PExpLogicaEsq
{
    private PExpLogicaEsq _expLogicaEsq_;
    private TMenor _menor_;
    private PExpLogicaDir _expLogicaDir_;

    public AExpeMenorExpLogicaEsq()
    {
        // Constructor
    }

    public AExpeMenorExpLogicaEsq(
        @SuppressWarnings("hiding") PExpLogicaEsq _expLogicaEsq_,
        @SuppressWarnings("hiding") TMenor _menor_,
        @SuppressWarnings("hiding") PExpLogicaDir _expLogicaDir_)
    {
        // Constructor
        setExpLogicaEsq(_expLogicaEsq_);

        setMenor(_menor_);

        setExpLogicaDir(_expLogicaDir_);

    }

    @Override
    public Object clone()
    {
        return new AExpeMenorExpLogicaEsq(
            cloneNode(this._expLogicaEsq_),
            cloneNode(this._menor_),
            cloneNode(this._expLogicaDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpeMenorExpLogicaEsq(this);
    }

    public PExpLogicaEsq getExpLogicaEsq()
    {
        return this._expLogicaEsq_;
    }

    public void setExpLogicaEsq(PExpLogicaEsq node)
    {
        if(this._expLogicaEsq_ != null)
        {
            this._expLogicaEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaEsq_ = node;
    }

    public TMenor getMenor()
    {
        return this._menor_;
    }

    public void setMenor(TMenor node)
    {
        if(this._menor_ != null)
        {
            this._menor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menor_ = node;
    }

    public PExpLogicaDir getExpLogicaDir()
    {
        return this._expLogicaDir_;
    }

    public void setExpLogicaDir(PExpLogicaDir node)
    {
        if(this._expLogicaDir_ != null)
        {
            this._expLogicaDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogicaEsq_)
            + toString(this._menor_)
            + toString(this._expLogicaDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogicaEsq_ == child)
        {
            this._expLogicaEsq_ = null;
            return;
        }

        if(this._menor_ == child)
        {
            this._menor_ = null;
            return;
        }

        if(this._expLogicaDir_ == child)
        {
            this._expLogicaDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogicaEsq_ == oldChild)
        {
            setExpLogicaEsq((PExpLogicaEsq) newChild);
            return;
        }

        if(this._menor_ == oldChild)
        {
            setMenor((TMenor) newChild);
            return;
        }

        if(this._expLogicaDir_ == oldChild)
        {
            setExpLogicaDir((PExpLogicaDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
