/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpeMenorExpLogicaFator extends PExpLogicaFator
{
    private PExpressaoEsq _expressaoEsq_;
    private TMenor _menor_;
    private PExpressaoDir _expressaoDir_;

    public AExpeMenorExpLogicaFator()
    {
        // Constructor
    }

    public AExpeMenorExpLogicaFator(
        @SuppressWarnings("hiding") PExpressaoEsq _expressaoEsq_,
        @SuppressWarnings("hiding") TMenor _menor_,
        @SuppressWarnings("hiding") PExpressaoDir _expressaoDir_)
    {
        // Constructor
        setExpressaoEsq(_expressaoEsq_);

        setMenor(_menor_);

        setExpressaoDir(_expressaoDir_);

    }

    @Override
    public Object clone()
    {
        return new AExpeMenorExpLogicaFator(
            cloneNode(this._expressaoEsq_),
            cloneNode(this._menor_),
            cloneNode(this._expressaoDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpeMenorExpLogicaFator(this);
    }

    public PExpressaoEsq getExpressaoEsq()
    {
        return this._expressaoEsq_;
    }

    public void setExpressaoEsq(PExpressaoEsq node)
    {
        if(this._expressaoEsq_ != null)
        {
            this._expressaoEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoEsq_ = node;
    }

    public TMenor getMenor()
    {
        return this._menor_;
    }

    public void setMenor(TMenor node)
    {
        if(this._menor_ != null)
        {
            this._menor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menor_ = node;
    }

    public PExpressaoDir getExpressaoDir()
    {
        return this._expressaoDir_;
    }

    public void setExpressaoDir(PExpressaoDir node)
    {
        if(this._expressaoDir_ != null)
        {
            this._expressaoDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoEsq_)
            + toString(this._menor_)
            + toString(this._expressaoDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoEsq_ == child)
        {
            this._expressaoEsq_ = null;
            return;
        }

        if(this._menor_ == child)
        {
            this._menor_ = null;
            return;
        }

        if(this._expressaoDir_ == child)
        {
            this._expressaoDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoEsq_ == oldChild)
        {
            setExpressaoEsq((PExpressaoEsq) newChild);
            return;
        }

        if(this._menor_ == oldChild)
        {
            setMenor((TMenor) newChild);
            return;
        }

        if(this._expressaoDir_ == oldChild)
        {
            setExpressaoDir((PExpressaoDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
