/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpeMaiorExpLogicaFator extends PExpLogicaFator
{
    private PExpressaoEsq _expressaoEsq_;
    private TMaior _maior_;
    private PExpressaoDir _expressaoDir_;

    public AExpeMaiorExpLogicaFator()
    {
        // Constructor
    }

    public AExpeMaiorExpLogicaFator(
        @SuppressWarnings("hiding") PExpressaoEsq _expressaoEsq_,
        @SuppressWarnings("hiding") TMaior _maior_,
        @SuppressWarnings("hiding") PExpressaoDir _expressaoDir_)
    {
        // Constructor
        setExpressaoEsq(_expressaoEsq_);

        setMaior(_maior_);

        setExpressaoDir(_expressaoDir_);

    }

    @Override
    public Object clone()
    {
        return new AExpeMaiorExpLogicaFator(
            cloneNode(this._expressaoEsq_),
            cloneNode(this._maior_),
            cloneNode(this._expressaoDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpeMaiorExpLogicaFator(this);
    }

    public PExpressaoEsq getExpressaoEsq()
    {
        return this._expressaoEsq_;
    }

    public void setExpressaoEsq(PExpressaoEsq node)
    {
        if(this._expressaoEsq_ != null)
        {
            this._expressaoEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoEsq_ = node;
    }

    public TMaior getMaior()
    {
        return this._maior_;
    }

    public void setMaior(TMaior node)
    {
        if(this._maior_ != null)
        {
            this._maior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maior_ = node;
    }

    public PExpressaoDir getExpressaoDir()
    {
        return this._expressaoDir_;
    }

    public void setExpressaoDir(PExpressaoDir node)
    {
        if(this._expressaoDir_ != null)
        {
            this._expressaoDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoEsq_)
            + toString(this._maior_)
            + toString(this._expressaoDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoEsq_ == child)
        {
            this._expressaoEsq_ = null;
            return;
        }

        if(this._maior_ == child)
        {
            this._maior_ = null;
            return;
        }

        if(this._expressaoDir_ == child)
        {
            this._expressaoDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoEsq_ == oldChild)
        {
            setExpressaoEsq((PExpressaoEsq) newChild);
            return;
        }

        if(this._maior_ == oldChild)
        {
            setMaior((TMaior) newChild);
            return;
        }

        if(this._expressaoDir_ == oldChild)
        {
            setExpressaoDir((PExpressaoDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
