/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpeMaioreqExpLogicaFator extends PExpLogicaFator
{
    private PExpressaoEsq _expressaoEsq_;
    private TMaioreq _maioreq_;
    private PExpressaoDir _expressaoDir_;

    public AExpeMaioreqExpLogicaFator()
    {
        // Constructor
    }

    public AExpeMaioreqExpLogicaFator(
        @SuppressWarnings("hiding") PExpressaoEsq _expressaoEsq_,
        @SuppressWarnings("hiding") TMaioreq _maioreq_,
        @SuppressWarnings("hiding") PExpressaoDir _expressaoDir_)
    {
        // Constructor
        setExpressaoEsq(_expressaoEsq_);

        setMaioreq(_maioreq_);

        setExpressaoDir(_expressaoDir_);

    }

    @Override
    public Object clone()
    {
        return new AExpeMaioreqExpLogicaFator(
            cloneNode(this._expressaoEsq_),
            cloneNode(this._maioreq_),
            cloneNode(this._expressaoDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpeMaioreqExpLogicaFator(this);
    }

    public PExpressaoEsq getExpressaoEsq()
    {
        return this._expressaoEsq_;
    }

    public void setExpressaoEsq(PExpressaoEsq node)
    {
        if(this._expressaoEsq_ != null)
        {
            this._expressaoEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoEsq_ = node;
    }

    public TMaioreq getMaioreq()
    {
        return this._maioreq_;
    }

    public void setMaioreq(TMaioreq node)
    {
        if(this._maioreq_ != null)
        {
            this._maioreq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maioreq_ = node;
    }

    public PExpressaoDir getExpressaoDir()
    {
        return this._expressaoDir_;
    }

    public void setExpressaoDir(PExpressaoDir node)
    {
        if(this._expressaoDir_ != null)
        {
            this._expressaoDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoEsq_)
            + toString(this._maioreq_)
            + toString(this._expressaoDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoEsq_ == child)
        {
            this._expressaoEsq_ = null;
            return;
        }

        if(this._maioreq_ == child)
        {
            this._maioreq_ = null;
            return;
        }

        if(this._expressaoDir_ == child)
        {
            this._expressaoDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoEsq_ == oldChild)
        {
            setExpressaoEsq((PExpressaoEsq) newChild);
            return;
        }

        if(this._maioreq_ == oldChild)
        {
            setMaioreq((TMaioreq) newChild);
            return;
        }

        if(this._expressaoDir_ == oldChild)
        {
            setExpressaoDir((PExpressaoDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
