/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpDirExpressaoEsq extends PExpressaoEsq
{
    private PExpressaoDir _expressaoDir_;

    public AExpDirExpressaoEsq()
    {
        // Constructor
    }

    public AExpDirExpressaoEsq(
        @SuppressWarnings("hiding") PExpressaoDir _expressaoDir_)
    {
        // Constructor
        setExpressaoDir(_expressaoDir_);

    }

    @Override
    public Object clone()
    {
        return new AExpDirExpressaoEsq(
            cloneNode(this._expressaoDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpDirExpressaoEsq(this);
    }

    public PExpressaoDir getExpressaoDir()
    {
        return this._expressaoDir_;
    }

    public void setExpressaoDir(PExpressaoDir node)
    {
        if(this._expressaoDir_ != null)
        {
            this._expressaoDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoDir_ == child)
        {
            this._expressaoDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoDir_ == oldChild)
        {
            setExpressaoDir((PExpressaoDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
