/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpdAninhadaExpLogicaDir extends PExpLogicaDir
{
    private TAparentese _aparentese_;
    private PExpLogicaDir _expLogicaDir_;
    private TFparentese _fparentese_;

    public AExpdAninhadaExpLogicaDir()
    {
        // Constructor
    }

    public AExpdAninhadaExpLogicaDir(
        @SuppressWarnings("hiding") TAparentese _aparentese_,
        @SuppressWarnings("hiding") PExpLogicaDir _expLogicaDir_,
        @SuppressWarnings("hiding") TFparentese _fparentese_)
    {
        // Constructor
        setAparentese(_aparentese_);

        setExpLogicaDir(_expLogicaDir_);

        setFparentese(_fparentese_);

    }

    @Override
    public Object clone()
    {
        return new AExpdAninhadaExpLogicaDir(
            cloneNode(this._aparentese_),
            cloneNode(this._expLogicaDir_),
            cloneNode(this._fparentese_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpdAninhadaExpLogicaDir(this);
    }

    public TAparentese getAparentese()
    {
        return this._aparentese_;
    }

    public void setAparentese(TAparentese node)
    {
        if(this._aparentese_ != null)
        {
            this._aparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aparentese_ = node;
    }

    public PExpLogicaDir getExpLogicaDir()
    {
        return this._expLogicaDir_;
    }

    public void setExpLogicaDir(PExpLogicaDir node)
    {
        if(this._expLogicaDir_ != null)
        {
            this._expLogicaDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaDir_ = node;
    }

    public TFparentese getFparentese()
    {
        return this._fparentese_;
    }

    public void setFparentese(TFparentese node)
    {
        if(this._fparentese_ != null)
        {
            this._fparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fparentese_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aparentese_)
            + toString(this._expLogicaDir_)
            + toString(this._fparentese_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aparentese_ == child)
        {
            this._aparentese_ = null;
            return;
        }

        if(this._expLogicaDir_ == child)
        {
            this._expLogicaDir_ = null;
            return;
        }

        if(this._fparentese_ == child)
        {
            this._fparentese_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aparentese_ == oldChild)
        {
            setAparentese((TAparentese) newChild);
            return;
        }

        if(this._expLogicaDir_ == oldChild)
        {
            setExpLogicaDir((PExpLogicaDir) newChild);
            return;
        }

        if(this._fparentese_ == oldChild)
        {
            setFparentese((TFparentese) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
