/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpExp2Expressao extends PExpressao
{
    private PExpressao2 _expressao2_;

    public AExpExp2Expressao()
    {
        // Constructor
    }

    public AExpExp2Expressao(
        @SuppressWarnings("hiding") PExpressao2 _expressao2_)
    {
        // Constructor
        setExpressao2(_expressao2_);

    }

    @Override
    public Object clone()
    {
        return new AExpExp2Expressao(
            cloneNode(this._expressao2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpExp2Expressao(this);
    }

    public PExpressao2 getExpressao2()
    {
        return this._expressao2_;
    }

    public void setExpressao2(PExpressao2 node)
    {
        if(this._expressao2_ != null)
        {
            this._expressao2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressao2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressao2_ == child)
        {
            this._expressao2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressao2_ == oldChild)
        {
            setExpressao2((PExpressao2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
