/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AFatorAninhadoFatorExp extends PFatorExp
{
    private TAparentese _aparentese_;
    private PFatorExp _fatorExp_;
    private TFparentese _fparentese_;

    public AFatorAninhadoFatorExp()
    {
        // Constructor
    }

    public AFatorAninhadoFatorExp(
        @SuppressWarnings("hiding") TAparentese _aparentese_,
        @SuppressWarnings("hiding") PFatorExp _fatorExp_,
        @SuppressWarnings("hiding") TFparentese _fparentese_)
    {
        // Constructor
        setAparentese(_aparentese_);

        setFatorExp(_fatorExp_);

        setFparentese(_fparentese_);

    }

    @Override
    public Object clone()
    {
        return new AFatorAninhadoFatorExp(
            cloneNode(this._aparentese_),
            cloneNode(this._fatorExp_),
            cloneNode(this._fparentese_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatorAninhadoFatorExp(this);
    }

    public TAparentese getAparentese()
    {
        return this._aparentese_;
    }

    public void setAparentese(TAparentese node)
    {
        if(this._aparentese_ != null)
        {
            this._aparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aparentese_ = node;
    }

    public PFatorExp getFatorExp()
    {
        return this._fatorExp_;
    }

    public void setFatorExp(PFatorExp node)
    {
        if(this._fatorExp_ != null)
        {
            this._fatorExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fatorExp_ = node;
    }

    public TFparentese getFparentese()
    {
        return this._fparentese_;
    }

    public void setFparentese(TFparentese node)
    {
        if(this._fparentese_ != null)
        {
            this._fparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fparentese_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aparentese_)
            + toString(this._fatorExp_)
            + toString(this._fparentese_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aparentese_ == child)
        {
            this._aparentese_ = null;
            return;
        }

        if(this._fatorExp_ == child)
        {
            this._fatorExp_ = null;
            return;
        }

        if(this._fparentese_ == child)
        {
            this._fparentese_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aparentese_ == oldChild)
        {
            setAparentese((TAparentese) newChild);
            return;
        }

        if(this._fatorExp_ == oldChild)
        {
            setFatorExp((PFatorExp) newChild);
            return;
        }

        if(this._fparentese_ == oldChild)
        {
            setFparentese((TFparentese) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
