/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AFatorNegativoExpressaoFator extends PExpressaoFator
{
    private TSub _sub_;
    private PExpressaoFator _expressaoFator_;

    public AFatorNegativoExpressaoFator()
    {
        // Constructor
    }

    public AFatorNegativoExpressaoFator(
        @SuppressWarnings("hiding") TSub _sub_,
        @SuppressWarnings("hiding") PExpressaoFator _expressaoFator_)
    {
        // Constructor
        setSub(_sub_);

        setExpressaoFator(_expressaoFator_);

    }

    @Override
    public Object clone()
    {
        return new AFatorNegativoExpressaoFator(
            cloneNode(this._sub_),
            cloneNode(this._expressaoFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatorNegativoExpressaoFator(this);
    }

    public TSub getSub()
    {
        return this._sub_;
    }

    public void setSub(TSub node)
    {
        if(this._sub_ != null)
        {
            this._sub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sub_ = node;
    }

    public PExpressaoFator getExpressaoFator()
    {
        return this._expressaoFator_;
    }

    public void setExpressaoFator(PExpressaoFator node)
    {
        if(this._expressaoFator_ != null)
        {
            this._expressaoFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sub_)
            + toString(this._expressaoFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sub_ == child)
        {
            this._sub_ = null;
            return;
        }

        if(this._expressaoFator_ == child)
        {
            this._expressaoFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sub_ == oldChild)
        {
            setSub((TSub) newChild);
            return;
        }

        if(this._expressaoFator_ == oldChild)
        {
            setExpressaoFator((PExpressaoFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
