/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AFatorExpLogicaOu extends PExpLogicaOu
{
    private PExpLogicaFator _expLogicaFator_;

    public AFatorExpLogicaOu()
    {
        // Constructor
    }

    public AFatorExpLogicaOu(
        @SuppressWarnings("hiding") PExpLogicaFator _expLogicaFator_)
    {
        // Constructor
        setExpLogicaFator(_expLogicaFator_);

    }

    @Override
    public Object clone()
    {
        return new AFatorExpLogicaOu(
            cloneNode(this._expLogicaFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatorExpLogicaOu(this);
    }

    public PExpLogicaFator getExpLogicaFator()
    {
        return this._expLogicaFator_;
    }

    public void setExpLogicaFator(PExpLogicaFator node)
    {
        if(this._expLogicaFator_ != null)
        {
            this._expLogicaFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogicaFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogicaFator_ == child)
        {
            this._expLogicaFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogicaFator_ == oldChild)
        {
            setExpLogicaFator((PExpLogicaFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
