/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorExpLogicaMaior extends PExpLogicaMaior
{
    private PExp _exp_;
    private TMaior _maior_;
    private PExpLogicaMenor _expLogicaMenor_;

    public AMaiorExpLogicaMaior()
    {
        // Constructor
    }

    public AMaiorExpLogicaMaior(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMaior _maior_,
        @SuppressWarnings("hiding") PExpLogicaMenor _expLogicaMenor_)
    {
        // Constructor
        setExp(_exp_);

        setMaior(_maior_);

        setExpLogicaMenor(_expLogicaMenor_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorExpLogicaMaior(
            cloneNode(this._exp_),
            cloneNode(this._maior_),
            cloneNode(this._expLogicaMenor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorExpLogicaMaior(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMaior getMaior()
    {
        return this._maior_;
    }

    public void setMaior(TMaior node)
    {
        if(this._maior_ != null)
        {
            this._maior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maior_ = node;
    }

    public PExpLogicaMenor getExpLogicaMenor()
    {
        return this._expLogicaMenor_;
    }

    public void setExpLogicaMenor(PExpLogicaMenor node)
    {
        if(this._expLogicaMenor_ != null)
        {
            this._expLogicaMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaMenor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._maior_)
            + toString(this._expLogicaMenor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._maior_ == child)
        {
            this._maior_ = null;
            return;
        }

        if(this._expLogicaMenor_ == child)
        {
            this._expLogicaMenor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._maior_ == oldChild)
        {
            setMaior((TMaior) newChild);
            return;
        }

        if(this._expLogicaMenor_ == oldChild)
        {
            setExpLogicaMenor((PExpLogicaMenor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
