/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AMenorqExpLogicaMaiorq extends PExpLogicaMaiorq
{
    private PExpLogicaMenorq _expLogicaMenorq_;

    public AMenorqExpLogicaMaiorq()
    {
        // Constructor
    }

    public AMenorqExpLogicaMaiorq(
        @SuppressWarnings("hiding") PExpLogicaMenorq _expLogicaMenorq_)
    {
        // Constructor
        setExpLogicaMenorq(_expLogicaMenorq_);

    }

    @Override
    public Object clone()
    {
        return new AMenorqExpLogicaMaiorq(
            cloneNode(this._expLogicaMenorq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorqExpLogicaMaiorq(this);
    }

    public PExpLogicaMenorq getExpLogicaMenorq()
    {
        return this._expLogicaMenorq_;
    }

    public void setExpLogicaMenorq(PExpLogicaMenorq node)
    {
        if(this._expLogicaMenorq_ != null)
        {
            this._expLogicaMenorq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaMenorq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogicaMenorq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogicaMenorq_ == child)
        {
            this._expLogicaMenorq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogicaMenorq_ == oldChild)
        {
            setExpLogicaMenorq((PExpLogicaMenorq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
