/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AOrExpLogicaDir extends PExpLogicaDir
{
    private PExp _exp_;
    private TOu _ou_;
    private PExpLogicaFator _expLogicaFator_;

    public AOrExpLogicaDir()
    {
        // Constructor
    }

    public AOrExpLogicaDir(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PExpLogicaFator _expLogicaFator_)
    {
        // Constructor
        setExp(_exp_);

        setOu(_ou_);

        setExpLogicaFator(_expLogicaFator_);

    }

    @Override
    public Object clone()
    {
        return new AOrExpLogicaDir(
            cloneNode(this._exp_),
            cloneNode(this._ou_),
            cloneNode(this._expLogicaFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExpLogicaDir(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PExpLogicaFator getExpLogicaFator()
    {
        return this._expLogicaFator_;
    }

    public void setExpLogicaFator(PExpLogicaFator node)
    {
        if(this._expLogicaFator_ != null)
        {
            this._expLogicaFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._ou_)
            + toString(this._expLogicaFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._expLogicaFator_ == child)
        {
            this._expLogicaFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._expLogicaFator_ == oldChild)
        {
            setExpLogicaFator((PExpLogicaFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
