/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ASemParenteseExpressaoLogica extends PExpressaoLogica
{
    private PExpLogicaEsq _expLogicaEsq_;

    public ASemParenteseExpressaoLogica()
    {
        // Constructor
    }

    public ASemParenteseExpressaoLogica(
        @SuppressWarnings("hiding") PExpLogicaEsq _expLogicaEsq_)
    {
        // Constructor
        setExpLogicaEsq(_expLogicaEsq_);

    }

    @Override
    public Object clone()
    {
        return new ASemParenteseExpressaoLogica(
            cloneNode(this._expLogicaEsq_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASemParenteseExpressaoLogica(this);
    }

    public PExpLogicaEsq getExpLogicaEsq()
    {
        return this._expLogicaEsq_;
    }

    public void setExpLogicaEsq(PExpLogicaEsq node)
    {
        if(this._expLogicaEsq_ != null)
        {
            this._expLogicaEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaEsq_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogicaEsq_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogicaEsq_ == child)
        {
            this._expLogicaEsq_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogicaEsq_ == oldChild)
        {
            setExpLogicaEsq((PExpLogicaEsq) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
