/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ASomaExpressaoEsq extends PExpressaoEsq
{
    private PExp _exp_;
    private TSum _sum_;
    private PExpressaoSub _expressaoSub_;

    public ASomaExpressaoEsq()
    {
        // Constructor
    }

    public ASomaExpressaoEsq(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TSum _sum_,
        @SuppressWarnings("hiding") PExpressaoSub _expressaoSub_)
    {
        // Constructor
        setExp(_exp_);

        setSum(_sum_);

        setExpressaoSub(_expressaoSub_);

    }

    @Override
    public Object clone()
    {
        return new ASomaExpressaoEsq(
            cloneNode(this._exp_),
            cloneNode(this._sum_),
            cloneNode(this._expressaoSub_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaExpressaoEsq(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TSum getSum()
    {
        return this._sum_;
    }

    public void setSum(TSum node)
    {
        if(this._sum_ != null)
        {
            this._sum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sum_ = node;
    }

    public PExpressaoSub getExpressaoSub()
    {
        return this._expressaoSub_;
    }

    public void setExpressaoSub(PExpressaoSub node)
    {
        if(this._expressaoSub_ != null)
        {
            this._expressaoSub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoSub_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._sum_)
            + toString(this._expressaoSub_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._sum_ == child)
        {
            this._sum_ = null;
            return;
        }

        if(this._expressaoSub_ == child)
        {
            this._expressaoSub_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._sum_ == oldChild)
        {
            setSum((TSum) newChild);
            return;
        }

        if(this._expressaoSub_ == oldChild)
        {
            setExpressaoSub((PExpressaoSub) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
