/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AUmaExpressaoExpEscreva extends PExpEscreva
{
    private PExpOuExplogica _expOuExplogica_;

    public AUmaExpressaoExpEscreva()
    {
        // Constructor
    }

    public AUmaExpressaoExpEscreva(
        @SuppressWarnings("hiding") PExpOuExplogica _expOuExplogica_)
    {
        // Constructor
        setExpOuExplogica(_expOuExplogica_);

    }

    @Override
    public Object clone()
    {
        return new AUmaExpressaoExpEscreva(
            cloneNode(this._expOuExplogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUmaExpressaoExpEscreva(this);
    }

    public PExpOuExplogica getExpOuExplogica()
    {
        return this._expOuExplogica_;
    }

    public void setExpOuExplogica(PExpOuExplogica node)
    {
        if(this._expOuExplogica_ != null)
        {
            this._expOuExplogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOuExplogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOuExplogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOuExplogica_ == child)
        {
            this._expOuExplogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOuExplogica_ == oldChild)
        {
            setExpOuExplogica((PExpOuExplogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
