/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVariavelNegativaExpressaoFinal extends PExpressaoFinal
{
    private TSub _sub_;
    private PExpressaoFinal _expressaoFinal_;

    public AVariavelNegativaExpressaoFinal()
    {
        // Constructor
    }

    public AVariavelNegativaExpressaoFinal(
        @SuppressWarnings("hiding") TSub _sub_,
        @SuppressWarnings("hiding") PExpressaoFinal _expressaoFinal_)
    {
        // Constructor
        setSub(_sub_);

        setExpressaoFinal(_expressaoFinal_);

    }

    @Override
    public Object clone()
    {
        return new AVariavelNegativaExpressaoFinal(
            cloneNode(this._sub_),
            cloneNode(this._expressaoFinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariavelNegativaExpressaoFinal(this);
    }

    public TSub getSub()
    {
        return this._sub_;
    }

    public void setSub(TSub node)
    {
        if(this._sub_ != null)
        {
            this._sub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sub_ = node;
    }

    public PExpressaoFinal getExpressaoFinal()
    {
        return this._expressaoFinal_;
    }

    public void setExpressaoFinal(PExpressaoFinal node)
    {
        if(this._expressaoFinal_ != null)
        {
            this._expressaoFinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoFinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sub_)
            + toString(this._expressaoFinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sub_ == child)
        {
            this._sub_ = null;
            return;
        }

        if(this._expressaoFinal_ == child)
        {
            this._expressaoFinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sub_ == oldChild)
        {
            setSub((TSub) newChild);
            return;
        }

        if(this._expressaoFinal_ == oldChild)
        {
            setExpressaoFinal((PExpressaoFinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
