/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVariasArgExp extends PArgExp
{
    private PExp _exp_;
    private TVirgula _virgula_;
    private PArgExp _argExp_;

    public AVariasArgExp()
    {
        // Constructor
    }

    public AVariasArgExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PArgExp _argExp_)
    {
        // Constructor
        setExp(_exp_);

        setVirgula(_virgula_);

        setArgExp(_argExp_);

    }

    @Override
    public Object clone()
    {
        return new AVariasArgExp(
            cloneNode(this._exp_),
            cloneNode(this._virgula_),
            cloneNode(this._argExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariasArgExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PArgExp getArgExp()
    {
        return this._argExp_;
    }

    public void setArgExp(PArgExp node)
    {
        if(this._argExp_ != null)
        {
            this._argExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._argExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._virgula_)
            + toString(this._argExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._argExp_ == child)
        {
            this._argExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._argExp_ == oldChild)
        {
            setArgExp((PArgExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
