/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVariasExpVariasExp extends PVariasExp
{
    private final LinkedList<PIndiceExp> _indiceExp_ = new LinkedList<PIndiceExp>();

    public AVariasExpVariasExp()
    {
        // Constructor
    }

    public AVariasExpVariasExp(
        @SuppressWarnings("hiding") List<?> _indiceExp_)
    {
        // Constructor
        setIndiceExp(_indiceExp_);

    }

    @Override
    public Object clone()
    {
        return new AVariasExpVariasExp(
            cloneList(this._indiceExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariasExpVariasExp(this);
    }

    public LinkedList<PIndiceExp> getIndiceExp()
    {
        return this._indiceExp_;
    }

    public void setIndiceExp(List<?> list)
    {
        for(PIndiceExp e : this._indiceExp_)
        {
            e.parent(null);
        }
        this._indiceExp_.clear();

        for(Object obj_e : list)
        {
            PIndiceExp e = (PIndiceExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._indiceExp_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._indiceExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._indiceExp_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PIndiceExp> i = this._indiceExp_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PIndiceExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
