/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.Analysis;

@SuppressWarnings("nls")
public final class AVariasVariaveisVar extends PVar
{
    private PVarOuVetor _varOuVetor_;
    private PVar _var_;

    public AVariasVariaveisVar()
    {
        // Constructor
    }

    public AVariasVariaveisVar(
        @SuppressWarnings("hiding") PVarOuVetor _varOuVetor_,
        @SuppressWarnings("hiding") PVar _var_)
    {
        // Constructor
        setVarOuVetor(_varOuVetor_);

        setVar(_var_);

    }

    @Override
    public Object clone()
    {
        return new AVariasVariaveisVar(
            cloneNode(this._varOuVetor_),
            cloneNode(this._var_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariasVariaveisVar(this);
    }

    public PVarOuVetor getVarOuVetor()
    {
        return this._varOuVetor_;
    }

    public void setVarOuVetor(PVarOuVetor node)
    {
        if(this._varOuVetor_ != null)
        {
            this._varOuVetor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varOuVetor_ = node;
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varOuVetor_)
            + toString(this._var_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varOuVetor_ == child)
        {
            this._varOuVetor_ = null;
            return;
        }

        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varOuVetor_ == oldChild)
        {
            setVarOuVetor((PVarOuVetor) newChild);
            return;
        }

        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
