/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVetoresDeclaracao extends PDeclaracao
{
    private PVetor _vetor_;

    public AVetoresDeclaracao()
    {
        // Constructor
    }

    public AVetoresDeclaracao(
        @SuppressWarnings("hiding") PVetor _vetor_)
    {
        // Constructor
        setVetor(_vetor_);

    }

    @Override
    public Object clone()
    {
        return new AVetoresDeclaracao(
            cloneNode(this._vetor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVetoresDeclaracao(this);
    }

    public PVetor getVetor()
    {
        return this._vetor_;
    }

    public void setVetor(PVetor node)
    {
        if(this._vetor_ != null)
        {
            this._vetor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vetor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vetor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vetor_ == child)
        {
            this._vetor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vetor_ == oldChild)
        {
            setVetor((PVetor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
