/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.Analysis;

@SuppressWarnings("nls")
public final class TComentariosimples extends Token
{
    public TComentariosimples()
    {
        super.setText("//");
    }

    public TComentariosimples(int line, int pos)
    {
        super.setText("//");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComentariosimples(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComentariosimples(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComentariosimples text.");
    }
}
