/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.Analysis;

@SuppressWarnings("nls")
public final class TPare extends Token
{
    public TPare()
    {
        super.setText("pare");
    }

    public TPare(int line, int pos)
    {
        super.setText("pare");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPare(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPare(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPare text.");
    }
}
