/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.Analysis;

@SuppressWarnings("nls")
public final class TTipocaractere extends Token
{
    public TTipocaractere()
    {
        super.setText("caractere");
    }

    public TTipocaractere(int line, int pos)
    {
        super.setText("caractere");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTipocaractere(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTipocaractere(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTipocaractere text.");
    }
}
