/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACasosAvalie extends PCasosAvalie
{
    private PCondComandoCasos _condComandoCasos_;
    private PComandoSenao _comandoSenao_;

    public ACasosAvalie()
    {
        // Constructor
    }

    public ACasosAvalie(
        @SuppressWarnings("hiding") PCondComandoCasos _condComandoCasos_,
        @SuppressWarnings("hiding") PComandoSenao _comandoSenao_)
    {
        // Constructor
        setCondComandoCasos(_condComandoCasos_);

        setComandoSenao(_comandoSenao_);

    }

    @Override
    public Object clone()
    {
        return new ACasosAvalie(
            cloneNode(this._condComandoCasos_),
            cloneNode(this._comandoSenao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACasosAvalie(this);
    }

    public PCondComandoCasos getCondComandoCasos()
    {
        return this._condComandoCasos_;
    }

    public void setCondComandoCasos(PCondComandoCasos node)
    {
        if(this._condComandoCasos_ != null)
        {
            this._condComandoCasos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condComandoCasos_ = node;
    }

    public PComandoSenao getComandoSenao()
    {
        return this._comandoSenao_;
    }

    public void setComandoSenao(PComandoSenao node)
    {
        if(this._comandoSenao_ != null)
        {
            this._comandoSenao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSenao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condComandoCasos_)
            + toString(this._comandoSenao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condComandoCasos_ == child)
        {
            this._condComandoCasos_ = null;
            return;
        }

        if(this._comandoSenao_ == child)
        {
            this._comandoSenao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condComandoCasos_ == oldChild)
        {
            setCondComandoCasos((PCondComandoCasos) newChild);
            return;
        }

        if(this._comandoSenao_ == oldChild)
        {
            setComandoSenao((PComandoSenao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
