/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVariosCasesCondComandoCasos extends PCondComandoCasos
{
    private final LinkedList<PComandoCaso> _comandoCaso_ = new LinkedList<PComandoCaso>();

    public AVariosCasesCondComandoCasos()
    {
        // Constructor
    }

    public AVariosCasesCondComandoCasos(
        @SuppressWarnings("hiding") List<?> _comandoCaso_)
    {
        // Constructor
        setComandoCaso(_comandoCaso_);

    }

    @Override
    public Object clone()
    {
        return new AVariosCasesCondComandoCasos(
            cloneList(this._comandoCaso_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariosCasesCondComandoCasos(this);
    }

    public LinkedList<PComandoCaso> getComandoCaso()
    {
        return this._comandoCaso_;
    }

    public void setComandoCaso(List<?> list)
    {
        for(PComandoCaso e : this._comandoCaso_)
        {
            e.parent(null);
        }
        this._comandoCaso_.clear();

        for(Object obj_e : list)
        {
            PComandoCaso e = (PComandoCaso) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comandoCaso_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoCaso_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoCaso_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PComandoCaso> i = this._comandoCaso_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandoCaso) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
