/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.lexer;

import java.io.*;
import compilador.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPara(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAvalie(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaso(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPare(line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreva(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNulo(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRetorne(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFaca(line, pos); }
    Token new16(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdadeiro(text, line, pos); }
    Token new17(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(text, line, pos); }
    Token new18(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(text, line, pos); }
    Token new19(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaioreq(text, line, pos); }
    Token new20(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorq(text, line, pos); }
    Token new21(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaior(text, line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSum(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSub(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new29(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNao(text, line, pos); }
    Token new30(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(text, line, pos); }
    Token new31(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(text, line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipointeiro(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTiporeal(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipocaractere(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipobooleano(line, pos); }
    Token new36(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(text, line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoevirgula(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechablococomentario(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreblococomentario(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoispontos(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentariosimples(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAparentese(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFparentese(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAcolchete(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFcolchete(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtrib(line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasimples(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasduplas(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNovalinha(text, line, pos); }
    Token new51(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }
    Token new52(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTab(text, line, pos); }
    Token new53(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRn(text, line, pos); }
    Token new54(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new55(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(text, line, pos); }
    Token new56(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(text, line, pos); }
    Token new57(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaractere(text, line, pos); }
    Token new58(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new59(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBooleano(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {37, 37, 6}, {39, 39, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {91, 91, 23}, {93, 93, 24}, {95, 95, 25}, {97, 97, 26}, {98, 98, 27}, {99, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 29}, {105, 105, 32}, {106, 107, 29}, {108, 108, 33}, {109, 109, 29}, {110, 110, 34}, {111, 111, 35}, {112, 112, 36}, {113, 113, 29}, {114, 114, 37}, {115, 115, 38}, {116, 117, 29}, {118, 118, 39}, {119, 122, 29}, },
            {},
            {},
            {{10, 10, 40}, },
            {{32, 32, 4}, },
            {},
            {},
            {{32, 32, 41}, {48, 57, 42}, {65, 90, 43}, {97, 122, 44}, },
            {},
            {},
            {{47, 47, 45}, },
            {},
            {},
            {},
            {},
            {{42, 42, 46}, {47, 47, 47}, },
            {{44, 44, 48}, {48, 57, 16}, },
            {},
            {{10, 10, 49}, },
            {{45, 45, 50}, {61, 61, 51}, {62, 62, 52}, },
            {},
            {{61, 61, 53}, },
            {{48, 57, 54}, {65, 90, 55}, {95, 95, 56}, {97, 122, 57}, },
            {},
            {},
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 117, 57}, {118, 118, 58}, {119, 122, 57}, },
            {{48, 95, -24}, {97, 110, 57}, {111, 111, 59}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 60}, {98, 110, 57}, {111, 111, 61}, {112, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 109, 57}, {110, 110, 62}, {111, 114, 57}, {115, 115, 63}, {116, 122, 57}, },
            {{48, 95, -24}, {97, 97, 64}, {98, 104, 57}, {105, 105, 65}, {106, 122, 57}, },
            {{48, 109, -32}, {110, 110, 66}, {111, 122, 57}, },
            {{48, 95, -24}, {97, 100, 57}, {101, 101, 67}, {102, 122, 57}, },
            {{48, 95, -24}, {97, 97, 68}, {98, 116, 57}, {117, 117, 69}, {118, 122, 57}, },
            {{48, 95, -24}, {97, 116, 57}, {117, 117, 70}, {118, 122, 57}, },
            {{48, 95, -24}, {97, 97, 71}, {98, 113, 57}, {114, 114, 72}, {115, 122, 57}, },
            {{48, 100, -35}, {101, 101, 73}, {102, 122, 57}, },
            {{48, 100, -35}, {101, 101, 74}, {102, 122, 57}, },
            {{48, 100, -35}, {101, 101, 75}, {102, 122, 57}, },
            {},
            {{32, 32, 41}, {39, 39, 76}, {48, 57, 42}, {65, 90, 77}, {97, 122, 78}, },
            {{32, 122, -43}, },
            {{32, 32, 41}, {39, 39, 79}, {48, 122, -43}, },
            {{32, 122, -45}, },
            {{10, 10, 80}, },
            {{10, 10, 81}, },
            {},
            {{48, 57, 82}, },
            {},
            {},
            {},
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 83}, {98, 122, 57}, },
            {{48, 110, -29}, {111, 111, 84}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 113, 57}, {114, 114, 85}, {115, 115, 86}, {116, 122, 57}, },
            {{48, 109, -32}, {110, 110, 87}, {111, 122, 57}, },
            {{48, 95, -24}, {97, 112, 57}, {113, 113, 88}, {114, 122, 57}, },
            {{48, 95, -24}, {97, 98, 57}, {99, 99, 89}, {100, 122, 57}, },
            {{48, 98, -65}, {99, 99, 90}, {100, 107, 57}, {108, 108, 91}, {109, 122, 57}, },
            {{48, 95, -24}, {97, 108, 57}, {109, 109, 92}, {110, 122, 57}, },
            {{48, 95, -24}, {97, 104, 57}, {105, 105, 93}, {106, 115, 57}, {116, 116, 94}, {117, 122, 57}, },
            {{48, 104, -68}, {105, 105, 95}, {106, 122, 57}, },
            {{48, 110, -29}, {111, 111, 96}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 107, 57}, {108, 108, 97}, {109, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 113, -62}, {114, 114, 98}, {115, 122, 57}, },
            {{48, 110, -29}, {111, 111, 99}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 100}, {98, 115, 57}, {116, 116, 101}, {117, 122, 57}, },
            {{48, 109, -32}, {110, 110, 102}, {111, 122, 57}, },
            {{48, 113, -62}, {114, 114, 103}, {115, 122, 57}, },
            {},
            {{32, 122, -43}, },
            {{32, 122, -43}, },
            {},
            {},
            {},
            {{48, 57, 82}, },
            {{48, 107, -71}, {108, 108, 104}, {109, 122, 57}, },
            {{48, 107, -71}, {108, 108, 105}, {109, 122, 57}, },
            {{48, 95, -24}, {97, 97, 106}, {98, 122, 57}, },
            {{48, 110, -29}, {111, 111, 107}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 114, 57}, {115, 115, 108}, {116, 122, 57}, },
            {{48, 116, -37}, {117, 117, 109}, {118, 122, 57}, },
            {{48, 113, -62}, {114, 114, 110}, {115, 122, 57}, },
            {{48, 95, -24}, {97, 97, 111}, {98, 122, 57}, },
            {{48, 114, -89}, {115, 115, 112}, {116, 122, 57}, },
            {{46, 46, 113}, {48, 122, -24}, },
            {{48, 98, -65}, {99, 99, 114}, {100, 122, 57}, },
            {{48, 100, -35}, {101, 101, 115}, {102, 122, 57}, },
            {{48, 95, -24}, {97, 97, 116}, {98, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 110, -29}, {111, 111, 117}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 118}, {98, 100, 57}, {101, 101, 119}, {102, 122, 57}, },
            {{48, 95, -24}, {97, 102, 57}, {103, 103, 120}, {104, 122, 57}, },
            {{48, 107, -71}, {108, 108, 121}, {109, 122, 57}, },
            {{48, 110, -29}, {111, 111, 122}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 123}, {98, 122, 57}, },
            {{48, 95, -24}, {97, 99, 57}, {100, 100, 124}, {101, 122, 57}, },
            {{48, 104, -68}, {105, 105, 125}, {106, 122, 57}, },
            {{48, 100, -35}, {101, 101, 126}, {102, 122, 57}, },
            {{48, 98, -65}, {99, 99, 127}, {100, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 115, 57}, {116, 116, 128}, {117, 122, 57}, },
            {{48, 95, -24}, {97, 97, 129}, {98, 122, 57}, },
            {{48, 100, -35}, {101, 101, 130}, {102, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 110, -29}, {111, 111, 131}, {112, 122, 57}, },
            {{10, 10, 132}, },
            {{48, 104, -68}, {105, 105, 133}, {106, 122, 57}, },
            {{48, 104, -68}, {105, 105, 134}, {106, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 113, -62}, {114, 114, 135}, {115, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 113, -62}, {114, 114, 136}, {115, 122, 57}, },
            {{48, 110, -29}, {111, 111, 137}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 138}, {98, 122, 57}, },
            {{48, 100, -35}, {101, 101, 139}, {102, 122, 57}, },
            {{48, 95, -24}, {97, 97, 140}, {98, 122, 57}, },
            {{48, 115, -110}, {116, 116, 141}, {117, 122, 57}, },
            {{48, 95, -24}, {97, 97, 142}, {98, 122, 57}, },
            {{48, 109, -32}, {110, 110, 143}, {111, 122, 57}, },
            {{48, 117, -28}, {118, 118, 144}, {119, 122, 57}, },
            {{48, 122, -24}, },
            {},
            {{48, 110, -29}, {111, 111, 145}, {112, 122, 57}, },
            {{48, 113, -62}, {114, 114, 146}, {115, 122, 57}, },
            {{48, 95, -24}, {97, 97, 147}, {98, 122, 57}, },
            {{48, 109, -32}, {110, 110, 148}, {111, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 99, -105}, {100, 100, 149}, {101, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 109, -32}, {110, 110, 150}, {111, 122, 57}, },
            {{48, 100, -35}, {101, 101, 151}, {102, 122, 57}, },
            {{48, 109, -32}, {110, 110, 152}, {111, 122, 57}, },
            {{48, 115, -110}, {116, 116, 153}, {117, 122, 57}, },
            {{48, 95, -24}, {97, 97, 154}, {98, 122, 57}, },
            {{10, 10, 155}, {48, 122, -24}, },
            {{48, 110, -29}, {111, 111, 156}, {112, 122, 57}, },
            {{48, 108, -67}, {109, 109, 157}, {110, 122, 57}, },
            {{48, 100, -35}, {101, 101, 158}, {102, 122, 57}, },
            {{48, 100, -35}, {101, 101, 159}, {102, 122, 57}, },
            {{48, 110, -29}, {111, 111, 160}, {112, 122, 57}, },
            {{48, 113, -62}, {114, 114, 161}, {115, 122, 57}, },
            {{48, 115, -110}, {116, 116, 162}, {117, 122, 57}, },
            {{48, 110, -29}, {111, 111, 163}, {112, 122, 57}, },
            {{48, 122, -24}, },
            {},
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 164}, {98, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 104, -68}, {105, 105, 165}, {106, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 100, -35}, {101, 101, 166}, {102, 122, 57}, },
            {{48, 100, -35}, {101, 101, 167}, {102, 122, 57}, },
            {{48, 122, -24}, },
            {{10, 10, 168}, {48, 122, -24}, },
            {{48, 113, -62}, {114, 114, 169}, {115, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {},
            {{48, 110, -29}, {111, 111, 170}, {112, 122, 57}, },
            {{48, 122, -24}, },
        }
        { // COMENTARIO_BLOCO
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {37, 37, 6}, {39, 39, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {91, 91, 23}, {93, 93, 24}, {95, 95, 25}, {97, 97, 26}, {98, 98, 27}, {99, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 29}, {105, 105, 32}, {106, 107, 29}, {108, 108, 33}, {109, 109, 29}, {110, 110, 34}, {111, 111, 35}, {112, 112, 36}, {113, 113, 29}, {114, 114, 37}, {115, 115, 38}, {116, 117, 29}, {118, 118, 39}, {119, 122, 29}, },
            {},
            {},
            {{10, 10, 40}, },
            {{32, 32, 4}, },
            {},
            {},
            {{32, 32, 41}, {48, 57, 42}, {65, 90, 43}, {97, 122, 44}, },
            {},
            {},
            {{47, 47, 45}, },
            {},
            {},
            {},
            {},
            {{42, 42, 46}, {47, 47, 47}, },
            {{44, 44, 48}, {48, 57, 16}, },
            {},
            {{10, 10, 49}, },
            {{45, 45, 50}, {61, 61, 51}, {62, 62, 52}, },
            {},
            {{61, 61, 53}, },
            {{48, 57, 54}, {65, 90, 55}, {95, 95, 56}, {97, 122, 57}, },
            {},
            {},
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 117, 57}, {118, 118, 58}, {119, 122, 57}, },
            {{48, 95, -24}, {97, 110, 57}, {111, 111, 59}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 60}, {98, 110, 57}, {111, 111, 61}, {112, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 109, 57}, {110, 110, 62}, {111, 114, 57}, {115, 115, 63}, {116, 122, 57}, },
            {{48, 95, -24}, {97, 97, 64}, {98, 104, 57}, {105, 105, 65}, {106, 122, 57}, },
            {{48, 109, -32}, {110, 110, 66}, {111, 122, 57}, },
            {{48, 95, -24}, {97, 100, 57}, {101, 101, 67}, {102, 122, 57}, },
            {{48, 95, -24}, {97, 97, 68}, {98, 116, 57}, {117, 117, 69}, {118, 122, 57}, },
            {{48, 95, -24}, {97, 116, 57}, {117, 117, 70}, {118, 122, 57}, },
            {{48, 95, -24}, {97, 97, 71}, {98, 113, 57}, {114, 114, 72}, {115, 122, 57}, },
            {{48, 100, -35}, {101, 101, 73}, {102, 122, 57}, },
            {{48, 100, -35}, {101, 101, 74}, {102, 122, 57}, },
            {{48, 100, -35}, {101, 101, 75}, {102, 122, 57}, },
            {},
            {{32, 32, 41}, {39, 39, 76}, {48, 57, 42}, {65, 90, 77}, {97, 122, 78}, },
            {{32, 122, -43}, },
            {{32, 32, 41}, {39, 39, 79}, {48, 122, -43}, },
            {{32, 122, -45}, },
            {{10, 10, 80}, },
            {{10, 10, 81}, },
            {},
            {{48, 57, 82}, },
            {},
            {},
            {},
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 83}, {98, 122, 57}, },
            {{48, 110, -29}, {111, 111, 84}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 113, 57}, {114, 114, 85}, {115, 115, 86}, {116, 122, 57}, },
            {{48, 109, -32}, {110, 110, 87}, {111, 122, 57}, },
            {{48, 95, -24}, {97, 112, 57}, {113, 113, 88}, {114, 122, 57}, },
            {{48, 95, -24}, {97, 98, 57}, {99, 99, 89}, {100, 122, 57}, },
            {{48, 98, -65}, {99, 99, 90}, {100, 107, 57}, {108, 108, 91}, {109, 122, 57}, },
            {{48, 95, -24}, {97, 108, 57}, {109, 109, 92}, {110, 122, 57}, },
            {{48, 95, -24}, {97, 104, 57}, {105, 105, 93}, {106, 115, 57}, {116, 116, 94}, {117, 122, 57}, },
            {{48, 104, -68}, {105, 105, 95}, {106, 122, 57}, },
            {{48, 110, -29}, {111, 111, 96}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 107, 57}, {108, 108, 97}, {109, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 113, -62}, {114, 114, 98}, {115, 122, 57}, },
            {{48, 110, -29}, {111, 111, 99}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 100}, {98, 115, 57}, {116, 116, 101}, {117, 122, 57}, },
            {{48, 109, -32}, {110, 110, 102}, {111, 122, 57}, },
            {{48, 113, -62}, {114, 114, 103}, {115, 122, 57}, },
            {},
            {{32, 122, -43}, },
            {{32, 122, -43}, },
            {},
            {},
            {},
            {{48, 57, 82}, },
            {{48, 107, -71}, {108, 108, 104}, {109, 122, 57}, },
            {{48, 107, -71}, {108, 108, 105}, {109, 122, 57}, },
            {{48, 95, -24}, {97, 97, 106}, {98, 122, 57}, },
            {{48, 110, -29}, {111, 111, 107}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 114, 57}, {115, 115, 108}, {116, 122, 57}, },
            {{48, 116, -37}, {117, 117, 109}, {118, 122, 57}, },
            {{48, 113, -62}, {114, 114, 110}, {115, 122, 57}, },
            {{48, 95, -24}, {97, 97, 111}, {98, 122, 57}, },
            {{48, 114, -89}, {115, 115, 112}, {116, 122, 57}, },
            {{46, 46, 113}, {48, 122, -24}, },
            {{48, 98, -65}, {99, 99, 114}, {100, 122, 57}, },
            {{48, 100, -35}, {101, 101, 115}, {102, 122, 57}, },
            {{48, 95, -24}, {97, 97, 116}, {98, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 110, -29}, {111, 111, 117}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 118}, {98, 100, 57}, {101, 101, 119}, {102, 122, 57}, },
            {{48, 95, -24}, {97, 102, 57}, {103, 103, 120}, {104, 122, 57}, },
            {{48, 107, -71}, {108, 108, 121}, {109, 122, 57}, },
            {{48, 110, -29}, {111, 111, 122}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 123}, {98, 122, 57}, },
            {{48, 95, -24}, {97, 99, 57}, {100, 100, 124}, {101, 122, 57}, },
            {{48, 104, -68}, {105, 105, 125}, {106, 122, 57}, },
            {{48, 100, -35}, {101, 101, 126}, {102, 122, 57}, },
            {{48, 98, -65}, {99, 99, 127}, {100, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 115, 57}, {116, 116, 128}, {117, 122, 57}, },
            {{48, 95, -24}, {97, 97, 129}, {98, 122, 57}, },
            {{48, 100, -35}, {101, 101, 130}, {102, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 110, -29}, {111, 111, 131}, {112, 122, 57}, },
            {{10, 10, 132}, },
            {{48, 104, -68}, {105, 105, 133}, {106, 122, 57}, },
            {{48, 104, -68}, {105, 105, 134}, {106, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 113, -62}, {114, 114, 135}, {115, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 113, -62}, {114, 114, 136}, {115, 122, 57}, },
            {{48, 110, -29}, {111, 111, 137}, {112, 122, 57}, },
            {{48, 95, -24}, {97, 97, 138}, {98, 122, 57}, },
            {{48, 100, -35}, {101, 101, 139}, {102, 122, 57}, },
            {{48, 95, -24}, {97, 97, 140}, {98, 122, 57}, },
            {{48, 115, -110}, {116, 116, 141}, {117, 122, 57}, },
            {{48, 95, -24}, {97, 97, 142}, {98, 122, 57}, },
            {{48, 109, -32}, {110, 110, 143}, {111, 122, 57}, },
            {{48, 117, -28}, {118, 118, 144}, {119, 122, 57}, },
            {{48, 122, -24}, },
            {},
            {{48, 110, -29}, {111, 111, 145}, {112, 122, 57}, },
            {{48, 113, -62}, {114, 114, 146}, {115, 122, 57}, },
            {{48, 95, -24}, {97, 97, 147}, {98, 122, 57}, },
            {{48, 109, -32}, {110, 110, 148}, {111, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 99, -105}, {100, 100, 149}, {101, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 109, -32}, {110, 110, 150}, {111, 122, 57}, },
            {{48, 100, -35}, {101, 101, 151}, {102, 122, 57}, },
            {{48, 109, -32}, {110, 110, 152}, {111, 122, 57}, },
            {{48, 115, -110}, {116, 116, 153}, {117, 122, 57}, },
            {{48, 95, -24}, {97, 97, 154}, {98, 122, 57}, },
            {{10, 10, 155}, {48, 122, -24}, },
            {{48, 110, -29}, {111, 111, 156}, {112, 122, 57}, },
            {{48, 108, -67}, {109, 109, 157}, {110, 122, 57}, },
            {{48, 100, -35}, {101, 101, 158}, {102, 122, 57}, },
            {{48, 100, -35}, {101, 101, 159}, {102, 122, 57}, },
            {{48, 110, -29}, {111, 111, 160}, {112, 122, 57}, },
            {{48, 113, -62}, {114, 114, 161}, {115, 122, 57}, },
            {{48, 115, -110}, {116, 116, 162}, {117, 122, 57}, },
            {{48, 110, -29}, {111, 111, 163}, {112, 122, 57}, },
            {{48, 122, -24}, },
            {},
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 164}, {98, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 104, -68}, {105, 105, 165}, {106, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 100, -35}, {101, 101, 166}, {102, 122, 57}, },
            {{48, 100, -35}, {101, 101, 167}, {102, 122, 57}, },
            {{48, 122, -24}, },
            {{10, 10, 168}, {48, 122, -24}, },
            {{48, 113, -62}, {114, 114, 169}, {115, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {},
            {{48, 110, -29}, {111, 111, 170}, {112, 122, 57}, },
            {{48, 122, -24}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 52, 50, 53, 51, 49, 28, 48, 43, 44, 24, 26, 36, 27, 37, 25, 55, 41, 38, 22, 23, 21, 54, 45, 46, 54, 54, 54, 54, 54, 30, 54, 54, 54, 54, 54, 54, 54, 54, 54, 53, -1, -1, -1, -1, 39, 40, 42, -1, 38, 47, 20, 18, 19, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 31, 54, 54, 54, 2, 54, 58, -1, -1, 57, 39, 40, 56, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 29, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 7, 54, 54, 54, 15, 54, 1, 54, 54, 10, 13, 5, 8, 54, 33, 54, 54, 54, 54, 54, 54, 54, 54, 54, 17, 1, 54, 54, 54, 54, 3, 54, 6, 54, 54, 54, 54, 54, 0, 54, 54, 54, 54, 54, 54, 54, 54, 11, 0, 32, 54, 14, 54, 35, 54, 54, 4, 9, 54, 34, 12, 9, 54, 16, },
        // COMENTARIO_BLOCO
        {-1, 52, 50, 53, 51, 49, 28, 48, 43, 44, 24, 26, 36, 27, 37, 25, 55, 41, 38, 22, 23, 21, 54, 45, 46, 54, 54, 54, 54, 54, 30, 54, 54, 54, 54, 54, 54, 54, 54, 54, 53, -1, -1, -1, -1, 39, 40, 42, -1, 38, 47, 20, 18, 19, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 31, 54, 54, 54, 2, 54, 58, -1, -1, 57, 39, 40, 56, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 29, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 7, 54, 54, 54, 15, 54, 1, 54, 54, 10, 13, 5, 8, 54, 33, 54, 54, 54, 54, 54, 54, 54, 54, 54, 17, 1, 54, 54, 54, 54, 3, 54, 6, 54, 54, 54, 54, 54, 0, 54, 54, 54, 54, 54, 54, 54, 54, 11, 0, 32, 54, 14, 54, 35, 54, 54, 4, 9, 54, 34, 12, 9, 54, 16, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMENTARIO_BLOCO = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
